language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - libeigen3-dev
  homebrew:
    packages:
      - eigen

install:
  - wget https://computing.llnl.gov/projects/sundials/download/sundials-4.1.0.tar.gz
  - tar xzf sundials-4.1.0.tar.gz
  - cd sundials-4.1.0
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=${TRAVIS_BUILD_DIR}/usr .. 
  - make
  - make install
script:
  - cd ${TRAVIS_BUILD_DIR}
  - make all CXXFLAGS_EXTRA="-I${TRAVIS_BUILD_DIR}/usr/include -L${TRAVIS_BUILD_DIR}/usr/lib"
  - make tests
